matrix:
  include:
    - name: Generate static
      language: php
      php: 7.0
      install: composer install --no-ansi --no-interaction --no-progress --no-scripts --optimize-autoloader --classmap-authoritative
      before_script: php -S localhost:8000 -t web >/dev/null 2>&1 &
      script: php index.php
      deploy:
        provider: pages
        github-token: $GITHUB_TOKEN
        keep-history: false
        local-dir: static/
        on: "*"
        skip_cleanup: true
